In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/Deep Learning/DL_Mam/Churn_Modelling.csv")

In [ ]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
#Drop the columns (RowNumber,CustomerId,Surname)

In [ ]:
x = data.iloc[:,3:-1]

In [ ]:
x

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [ ]:
y = data.iloc[:,-1]

In [ ]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [ ]:
x.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [ ]:
from sklearn.preprocessing import OrdinalEncoder,StandardScaler

In [ ]:
oe = OrdinalEncoder()

In [ ]:
x.iloc[:,[1,2]] = oe.fit_transform(x.iloc[:,[1,2]])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3, random_state=1)

In [ ]:
sc = StandardScaler()

In [ ]:
xtrain

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
2228,644,0.0,0.0,37,8,0.00,2,1,0,20968.88
5910,481,0.0,0.0,39,6,0.00,1,1,1,24677.54
1950,680,0.0,0.0,37,10,123806.28,1,1,0,81776.84
2119,690,0.0,1.0,29,5,0.00,2,1,0,108577.97
5947,656,0.0,0.0,45,7,145933.27,1,1,1,199392.14
...,...,...,...,...,...,...,...,...,...,...
2895,621,1.0,1.0,47,7,107363.29,1,1,1,66799.28
7813,684,1.0,0.0,63,3,81245.79,1,1,0,69643.31
905,672,0.0,0.0,45,9,0.00,1,1,1,92027.69
5192,663,0.0,0.0,39,8,0.00,2,1,1,101168.90
235,763,1.0,1.0,42,6,100160.75,1,1,0,33462.94

In [ ]:
xtrain = sc.fit_transform(xtrain)

In [ ]:
xtest = sc.transform(xtest)

In [ ]:
import tensorflow as tf
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense

from sklearn.metrics import classification_report

In [ ]:
# 1 inisilization model
ann = Sequential()

In [ ]:
#2creating hiden layer
ann.add(Dense(units=6, activation= "relu"))
ann.add(Dense(units=1, activation= "sigmoid"))

In [ ]:
#3 establishing the connection
ann.compile(optimizer="adam",loss = "binary_crossentropy", metrics = ["accuracy"])

In [ ]:
#4 training model
ann.fit(xtrain,ytrain, batch_size = 30, epochs = 100)

Epoch 1/100
234/234 [==============================] - 1s 2ms/step - loss: 0.6577 - accuracy: 0.6056
Epoch 2/100
234/234 [==============================] - 0s 2ms/step - loss: 0.5197 - accuracy: 0.7920
Epoch 3/100
234/234 [==============================] - 0s 1ms/step - loss: 0.4699 - accuracy: 0.8046
Epoch 4/100
234/234 [==============================] - 0s 2ms/step - loss: 0.4450 - accuracy: 0.8103
Epoch 5/100
234/234 [==============================] - 0s 2ms/step - loss: 0.4334 - accuracy: 0.8117
Epoch 6/100
234/234 [==============================] - 0s 1ms/step - loss: 0.4276 - accuracy: 0.8141
Epoch 7/100
234/234 [==============================] - 0s 1ms/step - loss: 0.4233 - accuracy: 0.8181
Epoch 8/100
234/234 [==============================] - 0s 1ms/step - loss: 0.4190 - accuracy: 0.8239
Epoch 9/100
234/234 [==============================] - 0s 1ms/step - loss: 0.4137 - accuracy: 0.8274
Epoch 10/100
234/234 [==============================] - 0s 1ms/step - loss: 0.4076 - accuracy: 0.8310
Epoch 11/100
234/234 [==============================] - 0s 1ms/step - loss: 0.4006 - accuracy: 0.8343
Epoch 12/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3933 - accuracy: 0.8367
Epoch 13/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3862 - accuracy: 0.8424
Epoch 14/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3801 - accuracy: 0.8459
Epoch 15/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3747 - accuracy: 0.8510
Epoch 16/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3705 - accuracy: 0.8507
Epoch 17/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3670 - accuracy: 0.8526
Epoch 18/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3641 - accuracy: 0.8534
Epoch 19/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3615 - accuracy: 0.8543
Epoch 20/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3598 - accuracy: 0.8547
Epoch 21/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3584 - accuracy: 0.8549
Epoch 22/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3571 - accuracy: 0.8557
Epoch 23/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3560 - accuracy: 0.8556
Epoch 24/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3555 - accuracy: 0.8576
Epoch 25/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3546 - accuracy: 0.8551
Epoch 26/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3540 - accuracy: 0.8557
Epoch 27/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3534 - accuracy: 0.8570
Epoch 28/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3531 - accuracy: 0.8556
Epoch 29/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3525 - accuracy: 0.8567
Epoch 30/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3525 - accuracy: 0.8570
Epoch 31/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3518 - accuracy: 0.8561
Epoch 32/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3515 - accuracy: 0.8581
Epoch 33/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3514 - accuracy: 0.8583
Epoch 34/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3509 - accuracy: 0.8570
Epoch 35/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3508 - accuracy: 0.8574
Epoch 36/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3507 - accuracy: 0.8554
Epoch 37/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3504 - accuracy: 0.8586
Epoch 38/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3505 - accuracy: 0.8569
Epoch 39/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3503 - accuracy: 0.8587
Epoch 40/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3501 - accuracy: 0.8576
Epoch 41/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3500 - accuracy: 0.8559
Epoch 42/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3497 - accuracy: 0.8574
Epoch 43/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3497 - accuracy: 0.8580
Epoch 44/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3498 - accuracy: 0.8563
Epoch 45/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3495 - accuracy: 0.8569
Epoch 46/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3494 - accuracy: 0.8579
Epoch 47/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3493 - accuracy: 0.8576
Epoch 48/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3494 - accuracy: 0.8570
Epoch 49/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3493 - accuracy: 0.8584
Epoch 50/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3492 - accuracy: 0.8581
Epoch 51/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3490 - accuracy: 0.8579
Epoch 52/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3489 - accuracy: 0.8589
Epoch 53/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3491 - accuracy: 0.8590
Epoch 54/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3488 - accuracy: 0.8584
Epoch 55/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3489 - accuracy: 0.8577
Epoch 56/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3488 - accuracy: 0.8589
Epoch 57/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3487 - accuracy: 0.8593
Epoch 58/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3489 - accuracy: 0.8596
Epoch 59/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3484 - accuracy: 0.8586
Epoch 60/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3488 - accuracy: 0.8587
Epoch 61/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3485 - accuracy: 0.8587
Epoch 62/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3486 - accuracy: 0.8586
Epoch 63/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3484 - accuracy: 0.8594
Epoch 64/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3486 - accuracy: 0.8589
Epoch 65/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3485 - accuracy: 0.8584
Epoch 66/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3486 - accuracy: 0.8584
Epoch 67/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3485 - accuracy: 0.8596
Epoch 68/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3485 - accuracy: 0.8579
Epoch 69/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3482 - accuracy: 0.8581
Epoch 70/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3482 - accuracy: 0.8577
Epoch 71/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3480 - accuracy: 0.8587
Epoch 72/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3482 - accuracy: 0.8597
Epoch 73/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3482 - accuracy: 0.8594
Epoch 74/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3481 - accuracy: 0.8594
Epoch 75/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3480 - accuracy: 0.8593
Epoch 76/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3481 - accuracy: 0.8590
Epoch 77/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3480 - accuracy: 0.8579
Epoch 78/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3478 - accuracy: 0.8596
Epoch 79/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3481 - accuracy: 0.8604
Epoch 80/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3480 - accuracy: 0.8589
Epoch 81/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3479 - accuracy: 0.8590
Epoch 82/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3479 - accuracy: 0.8579
Epoch 83/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3479 - accuracy: 0.8590
Epoch 84/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3477 - accuracy: 0.8587
Epoch 85/100
234/234 [==============================] - 1s 2ms/step - loss: 0.3476 - accuracy: 0.8600
Epoch 86/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3477 - accuracy: 0.8594
Epoch 87/100
234/234 [==============================] - 1s 4ms/step - loss: 0.3478 - accuracy: 0.8594
Epoch 88/100
234/234 [==============================] - 1s 2ms/step - loss: 0.3478 - accuracy: 0.8596
Epoch 89/100
234/234 [==============================] - 1s 4ms/step - loss: 0.3475 - accuracy: 0.8587
Epoch 90/100
234/234 [==============================] - 1s 3ms/step - loss: 0.3476 - accuracy: 0.8591
Epoch 91/100
234/234 [==============================] - 1s 3ms/step - loss: 0.3474 - accuracy: 0.8604
Epoch 92/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3473 - accuracy: 0.8594
Epoch 93/100
234/234 [==============================] - 1s 2ms/step - loss: 0.3476 - accuracy: 0.8586
Epoch 94/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3476 - accuracy: 0.8591
Epoch 95/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3474 - accuracy: 0.8596
Epoch 96/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3475 - accuracy: 0.8597
Epoch 97/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3475 - accuracy: 0.8594
Epoch 98/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3472 - accuracy: 0.8591
Epoch 99/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3474 - accuracy: 0.8587
Epoch 100/100
234/234 [==============================] - 0s 1ms/step - loss: 0.3473 - accuracy: 0.8600

In [ ]:
#5 make prediction
ypred = ann.predict(xtest)

In [ ]:
ypred

array([[0.04851034],
       [0.13417941],
       [0.06239042],
       ...,
       [0.03478864],
       [0.0810506 ],
       [0.07307005]], dtype=float32)

In [ ]:
print(classification_report(ytest, ypred.round()))

              precision    recall  f1-score   support

           0       0.86      0.97      0.91      2373
           1       0.79      0.43      0.55       627

    accuracy                           0.86      3000
   macro avg       0.83      0.70      0.73      3000
weighted avg       0.85      0.86      0.84      3000

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lg = LogisticRegression()

In [ ]:
lg.fit(xtrain,ytrain)
pred=lg.predict(xtest)

In [ ]:
print(classification_report(ytest, pred))

              precision    recall  f1-score   support

           0       0.82      0.97      0.89      2373
           1       0.64      0.18      0.28       627

    accuracy                           0.81      3000
   macro avg       0.73      0.58      0.59      3000
weighted avg       0.78      0.81      0.76      3000